### ISSUE TITLE
Filter by untranslated

### ISSUE THREAD

**Issue by najdan** [b123400/xliffie#2]
Hi,

It would be nice to have filters for untranslated strings and translations with warnings which can be turned on/off in combination or separately. 

_Best regards,
Najdan Tomić_

**Comment by b123400** [comment]
This is implemented in 1.9
![Screenshot 2023-04-08 at 15 08 03](https://github.com/b123400/xliffie/assets/127193/b313dd69-2a57-496c-b99f-e873ef35299c)
