### ISSUE TITLE
Before you install FGTranslator install all the other pods

### ISSUE THREAD

**Issue by zdavatz** [b123400/xliffie#4]
For me FGTranslator did not install if I did not install all the other pod files first. 
So first I commented out this line:
`pod "FGTranslator", :git => "git@github.com:b123400/FGTranslator.git", :branch => "refactor"`
then I did "pod install" and then I commented above line back in. Then everything installed fine.

**Comment by b123400** [comment]
Hello! This library is few years old and IMO out of maintenance, I can understand if it doesn't build, but it's weird to see the installation order matters. What's the error message you got?

**Comment by zdavatz** [comment]
It did not find some github reference for git@github.com:b123400/FGTranslator.git
